apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bkhv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-bkhv@sha256:acd3ed124249f0eb29d152ff82a1c273114986687d29ffffdb25bf27acc3a2c7
        name: my-nodejs
        resources: {}
status: {}
